---
- hosts: xxx
  become: yes

  vars_files:
    - vars/main.yml

  vars:
    list_of_packages:
      - nfs-common
        
  tasks:
    - name: Install common NFS packages
      package:
        name: "{{ list_of_packages }}"
        state: latest

    - name: Create NFS directory
      file:
        path:
        state: 
        owner: 
        group: 
        mode:
