---
- hosts: xxx
  become: yes

  vars_files:
    - vars/main.yml

  vars:
    list_of_packages:
      - nfs-common
        
  tasks:
    - name: Install common NFS packages
      ansible.builtin.package:
        name: "{{ list_of_packages }}"
        state: latest

    - name: Create NFS directory
      xxx:
        path:
        state:
        owner:
        group:
        mode:
