---
- hosts: xxx
  become: yes

  vars_files:
    - vars/main.yml

  vars:
    list_of_packages:
      - nfs-common
      - libnfs-utils

  tasks:
    - name: Install common NFS packages
      ansible.builtin.xxx:
        name:
        state:

    - name: Create NFS directory
      ansible.builtin.xxx:
        path:
        state:
        owner:
        group:
        mode:
