---
- hosts:
  become: yes

  vars_files:
    - vars/main.yml
        
  tasks:
    - name: Install NFS server packages
      package:
      
    - name: Ensure NFS server is started and enabled at boot
      service:
      
    - name: Copy exports template to /etc/exports
      template:
      
  handlers:
    - name: Restart NFS server
      service: name=nfs-kernel-server state=restarted
