---
- hosts: xxx
  become: yes

  vars_files:
    - vars/main.yml

  vars:
    list_of_packages:
      - nfs-kernel-server
        
  tasks:
    - name: Install NFS server packages
      package:
        name: "{{ list_of_packages }}"
        state: latest
 
    - name: Ensure NFS server is started and enabled at boot
      service: name=nfs-kernel-server state=started enabled=yes
  
    - name: Copy exports.j2 template to /etc/exports
      template:
        src: 
        dest: 
      notify:

        
  handlers:
    - name: Restart NFS server
      service: name=nfs-kernel-server state=restarted
