---
- hosts: xxx
  become: yes

  vars_files:
    - vars/main.yml
    
  tasks:
     - name: Add an apt signing key
       ansible.builtin.xxx:
         url:
         keyring:
         state:

     - name: Add apt repository for Temurin JDK
       ansible.builtin.xxx:
         repo:
         state:
        
     - name: Install JDK 11
       ansible.builtin.package:
         name: temurin-11-jdk
         state: latest
